---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  deprecations_as_errors: true
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

transport:
  name: winrm
  elevated: true

verifier:
  name: inspec

platforms:
  - name: windows-2012r2
    driver:
      box: tas50/windows_2012r2
      customize:
        memory: 2048

suites:
  - name: default
    run_list:
      - recipe[chef_iis_85_hardening::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
